version: "3.9"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - internal
# Names our volume
volumes:
  my-db:
networks:
  internal:
    external: true
